### ISSUE TITLE
Linux下的字体渲染有误

### ISSUE THREAD

**Issue by FTS427** [DaiYu-233/YMCL.Avalonia#1]
如图，部分字体渲染错误
![图片](https://github.com/DaiYu-233/YMCL.Avalonia/assets/122330825/281e2b53-5102-44b7-8ffb-736b16015809)
![图片](https://github.com/DaiYu-233/YMCL.Avalonia/assets/122330825/e9cb36b5-736b-4364-b7db-c9d8d65d089b)

**Comment by DaiYu-233** [comment]
编码问题，已修复！等待下一次推送
