### ISSUE TITLE
对于一个启动器来说，程序是否太大了？

### ISSUE THREAD

**Issue by allMagicNB** [DaiYu-233/YMCL.Avalonia#2]
没有说这不好的意思，只是我在代码中一个 microsoftonline.com 都没搜到，对依赖项的依赖是否太强了？以至于让我感觉这就是一个套 UI 的启动器。
这会导致什么？这会让上游依赖项出现漏洞或重大 Bug 时，只能等着他们修完。
程序包含依赖项，导致体积增大，可以考虑将不完全使用的依赖自己删减，但仍保留声明。

**Comment by DaiYu-233** [comment]
大部分是UI的依赖 体积大的是框架 我已经在努力压缩了
