### ISSUE TITLE
什么微软式中文

### ISSUE THREAD

**Issue by E0x72-21** [DaiYu-233/YMCL.Avalonia#8]
![image](https://github.com/user-attachments/assets/29ef317d-d166-427e-8299-4b091cc88494)

**Comment by DaiYu-233** [comment]
emmmm 
但是它确实叫作运行时

运行时是指一个程序在运行（或者在被执行）的依赖。（摘自百度百科）

**Comment by E0x72-21** [comment]
> emmmm 但是它确实叫作运行时
> 
> 运行时是指一个程序在运行（或者在被执行）的依赖。（摘自百度百科）

我的评价是不如改成"java依赖项"或者"java环境"更直观，这个“运行时”对于一般用户来说太莫名其妙了

**Comment by VeryJokerJal** [comment]
> > emmmm 但是它确实叫作运行时
> > 运行时是指一个程序在运行（或者在被执行）的依赖。（摘自百度百科）
> 
> 我的评价是不如改成"java依赖项"或者"java环境"更直观，这个“运行时”对于一般用户来说太莫名其妙了

简而言之：
Java依赖项：外部库或框架，项目所需。
Java环境：开发和运行Java所需的所有工具和软件。
Java运行时：运行Java应用程序所需的环境。

**Comment by E0x72-21** [comment]
> > > emmmm 但是它确实叫作运行时
> > > 运行时是指一个程序在运行（或者在被执行）的依赖。（摘自百度百科）
> > 
> > 
> > 我的评价是不如改成"java依赖项"或者"java环境"更直观，这个“运行时”对于一般用户来说太莫名其妙了
> 
> 简而言之： Java依赖项：外部库或框架，项目所需。 Java环境：开发和运行Java所需的所有工具和软件。 Java运行时：运行Java应用程序所需的环境。

~~有一种争辩内存/外存/ram/rom/存储的美~~
